name: "Run tasks #1"

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ "tasks-1/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "tasks-1/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tasks-1
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Run project app with Gradle"
        run: ./gradlew :app:run --info
