name: "Build and check project"

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ "task-3/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "task-3/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task-3
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Check project library with Gradle"
        run: ./gradlew :lib:check --info
      - name: "Upload test reports as an action artifact"
        uses: actions/upload-artifact@v2
        with:
          name: kover-test-reports
          path: task-3/lib/build/reports/kover/html
